# Generated by Django 4.2.1 on 2023-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="slug",
            field=models.SlugField(verbose_name="URL"),
        ),
    ]
